name: Checks

env:
  CAIRO_LANG_VERSION: "0.13.1"
  # TODO(#1611)
  DEVNET_SHA: 4798b6d516d7559aae02773721ff5fcb50ffccb2 # v0.5.0-rc.4
  LEDGER_APP_SHA: 768a7b47b0da681b28112342edd76e2c9b292c4e # v2.3.1
  LEDGER_APP_DEV_TOOLS_SHA: a845b2ab0b5dd824133f73858f6f373edea85ec1bd828245bf50ce9700f33bcb # v4.5.0

on:
  push:
    branches:
      - master
      - development
      - tests
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  # ---------------------------------------------------------- #
  # ...................LINT-FORMAT-TYPECHECK.................. #
  # ---------------------------------------------------------- #

  lint-format-typecheck:
    name: Lint - Format - Typecheck
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install -E ledger

      - name: Check poetry.lock
        run: |
          poetry check --lock

      - name: Lint
        run: |
          poetry run poe lint

      - name: Format
        run: |
          poetry run poe format_check

      - name: Typecheck
        run: |
          poetry run poe typecheck

  # ---------------------------------------------------------- #
  # .......................SETUP-TESTS........................ #
  # ---------------------------------------------------------- #

  setup-tests:
    name: Setup Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:

      # ====================== SETUP ====================== #

      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      # ====================== CONTRACTS v2 ====================== #
      - name: Cache contracts v2
        id: cache-contracts_v2
        uses: actions/cache@v4
        with:
          path: starknet_py/tests/e2e/mock/contracts_v2/target
          key: ${{ runner.os }}-contracts-${{ hashFiles('starknet_py/tests/e2e/mock/contracts_v2') }}

      - name: Compile contracts v2
        if: steps.cache-contracts_v2.outputs.cache-hit != 'true'
        run: |
          poetry run poe compile_contracts v2

      # ====================== CONTRACTS v1 ====================== #

      - name: Cache contracts v1
        id: cache-contracts_v1
        uses: actions/cache@v4
        with:
          path: starknet_py/tests/e2e/mock/contracts_v1/target
          key: ${{ runner.os }}-contracts-${{ hashFiles('starknet_py/tests/e2e/mock/contracts_v1') }}

      - name: Compile contracts v1
        if: steps.cache-contracts_v1.outputs.cache-hit != 'true'
        run: |
          poetry run poe compile_contracts v1

      - name: Upload contracts artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contract-artifacts
          path: starknet_py/tests/e2e/mock/

  # ---------------------------------------------------------- #
  # .....................RUN-DOCS-TESTS....................... #
  # ---------------------------------------------------------- #

  run-docs-tests:
    name: Docs Tests
    needs: setup-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.12" ]
        run_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
               10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
               20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
               30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
               40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
               50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
               60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
               70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
               80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
               90, 91, 92, 93, 94, 95, 96, 97, 98, 99,
               100,101,102,103,104,105,106,107,108,109,
               110,111,112,113,114,115,116,117,118,119,
               120]
    steps:
      - uses: actions/checkout@v4

      - name: Download contracts
        uses: actions/download-artifact@v4
        with:
          name: contract-artifacts
          path: starknet_py/tests/e2e/mock/

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      # ====================== SETUP PYTHON ====================== #

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      # ====================== SETUP DEVNET ====================== #

      - name: Install devnet
        run: ./starknet_py/tests/install_devnet.sh

      # ====================== RUN TESTS ====================== #

      - uses: asdf-vm/actions/setup@v3

#     TODO(#1498): Remove below step once issue with compiled contracts is resolved
      - name: Compile contracts
        run: |
          poetry run poe compile_contracts v2
          poetry run poe compile_contracts v1

      - name: Run tests
        run: |
          poetry run poe test_ci_docs_v2
          poetry run poe test_ci_docs_v1


  
